const data = [
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Jeff Bezos',rank: 2,age: 58, source: 'Amazon',country: 'United States',total: 164.2,},
    {Name:'Bernard Arnault & family',rank: 3,age: 73, source: 'LVMH',country: 'France',total: 229.4,},
    {Name:'Bill Gates',rank: 4,age: 66, source: 'Microsoft',country: 'United States',total: 128.9,},
    {Name:'Warren Buffett',rank: 5,age: 91, source: 'Berkshire Hathaway',country: 'United States',total: 117.0,},
    {Name:'Larry Page',rank: 6,age: 48, source: 'Google',country: 'United States',total: 110.2,},
    {Name:'Sergey Brin',rank: 7,age: 48, source: 'Google',country: 'United States',total: 106.2,},
    {Name:'Larry Ellison',rank: 8,age: 77, source: 'Software',country: 'United States',total: 102.4,},
    {Name:'Steve Ballmer',rank: 9,age: 65, source: 'Microsoft',country: 'United States',total: 90.4,},
    {Name:'Gautam Adani & family',rank: 10,age: 59, source: 'infrastructure, commodities',country: 'india',total: 85.3,},
    {Name:'Mukesh Ambani',rank: 11,age: 64, source: 'diversified',country: 'India',total: 83.2,},
    {Name:'Carlos Slim Helu & family',rank: 12,age: 82, source: 'Telecom',country: 'Mexico',total: 80.1,},
    {Name:'Francoise Bettencourt Meyers & family',rank: 13,age: 68, source: 'L Oréal',country: 'France',total: 72.1,},
    {Name:'Michael Bloomberg',rank: 14,age: 80, source: 'Bloomberg LP',country: 'United States',total: 70.0,},
    {Name:'Mark Zuckerberg',rank: 15,age: 37, source: 'Facebook',country: 'United States',total: 69.0,},
    {Name:'Zhong Shanshan',rank: 16,age: 67, source: 'beverages, pharmaceuticals',country: 'China',total: 65.6,},
    {Name:'Jim Walton',rank: 17 ,age: 73, source: 'Walmart',country: 'United States',total: 65.3,},
    {Name:'Alice Walton',rank: 18,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
    {Name:'Elon Musk',rank: 1,age: 50, source: 'Tesla, SpaceX',country: 'United States',total: 229.4,},
]